on: [push, pull_request]
name: Test
jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: PHPStan
      uses: james-coder/phpstan-ga
      with:
        args: analyse src/ --level=5
